//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityAssociation
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyClassContainer
    {
        public MyClassContainer()
        {
            this.MyClasses = new HashSet<MyClass>();
        }
    
        public int MyClassContainerID { get; set; }
        public string Information { get; set; }
    
        public virtual ICollection<MyClass> MyClasses { get; set; }
    }
}
