//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityCard
    {
        public int IdentityCardId { get; set; }
        public string IDNumber { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
