//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookInfo()
        {
            this.BorrowReturn = new HashSet<BorrowReturn>();
            this.BookType = new HashSet<BookType>();
        }
    
        public string BookName { get; set; }
        public System.DateTime TimeIn { get; set; }
        public string Author { get; set; }
        public string Translator { get; set; }
        public string PageNumber { get; set; }
        public string Price { get; set; }
        public string Layout { get; set; }
        public string Press { get; set; }
        public long ISBN { get; set; }
        public string PubDate { get; set; }
        public string BookRemark { get; set; }
        public int Total { get; set; }
        public int Amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowReturn> BorrowReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookType> BookType { get; set; }
    }
}
