//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public long StuId { get; set; }
        public string StuName { get; set; }
        public string Sex { get; set; }
        public Nullable<int> ClassId { get; set; }
        public int RoleTypeId { get; set; }
        public string IdCardNum { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Part Part { get; set; }
        public virtual RoleType RoleType { get; set; }
    }
}
