//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public long TeacherId { get; set; }
        public string TeacherName { get; set; }
        public string Sex { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public int RoleTypeId { get; set; }
        public string IdCardNum { get; set; }
        public Nullable<int> Rank { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Part Part { get; set; }
        public virtual RoleType RoleType { get; set; }
    }
}
