//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyClass
    {
        public MyClass()
        {
            this.MyClassChilds = new HashSet<MyClassChild>();
        }
    
        public int MyClassID { get; set; }
        public int MyClassContainerID { get; set; }
        public string Information { get; set; }
    
        public virtual MyClassContainer MyClassContainer { get; set; }
        public virtual ICollection<MyClassChild> MyClassChilds { get; set; }
    }
}
