//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using LibraryModel;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LibraryEntities : DbContext
    {
        public LibraryEntities()
            : base("name=LibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<BookInfo> BookInfo { get; set; }
        public virtual DbSet<BookType> BookType { get; set; }
        public virtual DbSet<BorrowReturn> BorrowReturn { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Part> Part { get; set; }
        public virtual DbSet<Reader> Reader { get; set; }
        public virtual DbSet<RoleType> RoleType { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
    
        [DbFunction("LibraryEntities", "GetReaderType")]
        public virtual IQueryable<GetReaderType_Result> GetReaderType()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetReaderType_Result>("[LibraryEntities].[GetReaderType]()");
        }
    }
}
