//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string LoginId { get; set; }
        public string LoginPwd { get; set; }
        public string LoginType { get; set; }
        public string LoginRemark { get; set; }
    }
}
