//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowReturn
    {
        public int BorrowId { get; set; }
        public string BookId { get; set; }
        public string ReaderId { get; set; }
        public System.DateTime BorrowTime { get; set; }
        public System.DateTime ReturnTime { get; set; }
        public Nullable<System.DateTime> FactReturnTime { get; set; }
        public decimal Fine { get; set; }
        public int RenewCount { get; set; }
        public string BorrowRemark { get; set; }
    
        public virtual BookInfo BookInfo { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
