//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reader()
        {
            this.BorrowReturns = new HashSet<BorrowReturn>();
        }
    
        public string ReaderId { get; set; }
        public string ReaderName { get; set; }
        public System.DateTime TimeIn { get; set; }
        public System.DateTime TimeOut { get; set; }
        public int ReaderTypeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string IdentityCard { get; set; }
        public string Gender { get; set; }
        public string Special { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string ReaderRemark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowReturn> BorrowReturns { get; set; }
        public virtual Class Class { get; set; }
        public virtual Department Department { get; set; }
        public virtual ReaderType ReaderType { get; set; }
    }
}
