//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookReview
    {
        public int BookReviewId { get; set; }
        public string Review { get; set; }
        public int BookId { get; set; }
        public string ReaderName { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
